/*
NAVICAT MYSQL DATA TRANSFER

SOURCE SERVER         : LOCAL
SOURCE SERVER VERSION : 50611
SOURCE HOST           : LOCALHOST:3306
SOURCE DATABASE       : SHOP

TARGET SERVER TYPE    : MYSQL
TARGET SERVER VERSION : 50611
FILE ENCODING         : 65001

DATE: 2016-11-18 17:37:37
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR BS_DETAIL
-- ----------------------------
DROP TABLE IF EXISTS `BS_DETAIL`;
CREATE TABLE `BS_DETAIL` (
  `ID` VARCHAR(32) NOT NULL,
  `PRO_ID` VARCHAR(32) DEFAULT NULL,
  `PUR_ID` VARCHAR(32) DEFAULT NULL,
  `PRO_COUNT` INT(11) DEFAULT NULL,
  `PRO_PRICE` DECIMAL(8,2) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

-- ----------------------------
-- TABLE STRUCTURE FOR BS_PRODUCT
-- ----------------------------
DROP TABLE IF EXISTS `BS_PRODUCT`;
CREATE TABLE `BS_PRODUCT` (
  `ID` VARCHAR(32) NOT NULL,
  `PRO_NAME` VARCHAR(50) DEFAULT NULL,
  `PRO_PRICE` DECIMAL(8,2) DEFAULT NULL,
  `PRO_COUNT` INT(11) DEFAULT NULL,
  `MARK` VARCHAR(200) DEFAULT NULL,
  `MODIFIED` DATETIME DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

-- ----------------------------
-- TABLE STRUCTURE FOR BS_PURCHASE
-- ----------------------------
DROP TABLE IF EXISTS `BS_PURCHASE`;
CREATE TABLE `BS_PURCHASE` (
  `ID` VARCHAR(32) NOT NULL,
  `USER_ID` VARCHAR(32) DEFAULT NULL,
  `MONEY` DECIMAL(8,2) DEFAULT NULL,
  `ORDER_TIME` DATETIME DEFAULT NULL,
  `ADDRESS` VARCHAR(120) DEFAULT NULL,
  `SIGN_TIME` DATETIME DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

-- ----------------------------
-- TABLE STRUCTURE FOR REF_PERMISSION_RESOURCE
-- ----------------------------
DROP TABLE IF EXISTS `REF_PERMISSION_RESOURCE`;
CREATE TABLE `REF_PERMISSION_RESOURCE` (
  `ID` VARCHAR(20) DEFAULT NULL COMMENT 'ID',
  `PID` VARCHAR(20) DEFAULT NULL COMMENT '权限ID',
  `RID` VARCHAR(20) DEFAULT NULL COMMENT '资源ID'
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

-- ----------------------------
-- TABLE STRUCTURE FOR REF_ROLE_GROUP
-- ----------------------------
DROP TABLE IF EXISTS `REF_ROLE_GROUP`;
CREATE TABLE `REF_ROLE_GROUP` (
  `ID` VARCHAR(20) DEFAULT NULL COMMENT 'ID',
  `RID` VARCHAR(20) DEFAULT NULL COMMENT '角色ID',
  `GID` VARCHAR(20) DEFAULT NULL COMMENT '用户组ID'
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

-- ----------------------------
-- TABLE STRUCTURE FOR REF_ROLE_PERMISSION
-- ----------------------------
DROP TABLE IF EXISTS `REF_ROLE_PERMISSION`;
CREATE TABLE `REF_ROLE_PERMISSION` (
  `ID` VARCHAR(20) DEFAULT NULL COMMENT 'ID',
  `RID` VARCHAR(20) DEFAULT NULL COMMENT '角色ID',
  `PID` VARCHAR(20) DEFAULT NULL COMMENT '权限ID'
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

-- ----------------------------
-- TABLE STRUCTURE FOR REF_USER_REF_GROUP
-- ----------------------------
DROP TABLE IF EXISTS `REF_USER_REF_GROUP`;
CREATE TABLE `REF_USER_REF_GROUP` (
  `ID` VARCHAR(20) DEFAULT NULL COMMENT 'ID',
  `UID` VARCHAR(20) DEFAULT NULL COMMENT '用户ID',
  `GID` VARCHAR(20) DEFAULT NULL COMMENT '用户组ID'
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

-- ----------------------------
-- TABLE STRUCTURE FOR REF_USER_ROLE
-- ----------------------------
DROP TABLE IF EXISTS `REF_USER_ROLE`;
CREATE TABLE `REF_USER_ROLE` (
  `ID` VARCHAR(20) DEFAULT NULL COMMENT 'ID',
  `UID` VARCHAR(20) DEFAULT NULL COMMENT '用户ID',
  `RID` VARCHAR(20) DEFAULT NULL COMMENT '角色ID'
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

-- ----------------------------
-- TABLE STRUCTURE FOR SYS_GROUP
-- ----------------------------
DROP TABLE IF EXISTS `SYS_GROUP`;
CREATE TABLE `SYS_GROUP` (
  `ID` VARCHAR(20) DEFAULT NULL COMMENT 'ID',
  `P_GID` VARCHAR(20) DEFAULT NULL COMMENT '父组',
  `NAME` VARCHAR(50) DEFAULT NULL COMMENT '组名称',
  `CREATE_TIME` DATETIME DEFAULT NULL COMMENT '创建时间',
  `REMARK` VARCHAR(200) DEFAULT NULL COMMENT '描述'
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='组表';

-- ----------------------------
-- TABLE STRUCTURE FOR SYS_PERMISSION
-- ----------------------------
DROP TABLE IF EXISTS `SYS_PERMISSION`;
CREATE TABLE `SYS_PERMISSION` (
  `ID` VARCHAR(20) DEFAULT NULL COMMENT 'ID',
  `ACCESS` VARCHAR(50) DEFAULT NULL COMMENT '权限',
  `REMARK` VARCHAR(200) DEFAULT NULL COMMENT '描述'
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='权限';

-- ----------------------------
-- TABLE STRUCTURE FOR SYS_RESOURCE
-- ----------------------------
DROP TABLE IF EXISTS `SYS_RESOURCE`;
CREATE TABLE `SYS_RESOURCE` (
  `ID` VARCHAR(20) DEFAULT NULL COMMENT 'ID',
  `NAME` VARCHAR(50) DEFAULT NULL COMMENT '名称',
  `TYPE` VARCHAR(15) DEFAULT NULL COMMENT '类型',
  `URL` VARCHAR(100) DEFAULT NULL COMMENT 'URL地址',
  `PARENT_ID` VARCHAR(50) DEFAULT NULL COMMENT '父节点',
  `PARENT_IDS` VARCHAR(100) DEFAULT NULL COMMENT '父节点组',
  `SORT` INT(5) DEFAULT NULL COMMENT '排序',
  `AVAILABLE` TINYINT(1) DEFAULT NULL COMMENT '是否生效'
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='资源';

-- ----------------------------
-- TABLE STRUCTURE FOR SYS_ROLE
-- ----------------------------
DROP TABLE IF EXISTS `SYS_ROLE`;
CREATE TABLE `SYS_ROLE` (
  `ID` VARCHAR(20) DEFAULT NULL COMMENT 'ID',
  `NAME` VARCHAR(50) DEFAULT NULL COMMENT '角色名称',
  `CREATE_TIME` DATETIME DEFAULT NULL COMMENT '创建时间',
  `REMARK` VARCHAR(200) DEFAULT NULL COMMENT '描述'
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT=' 角色表';

-- ----------------------------
-- TABLE STRUCTURE FOR SYS_USER
-- ----------------------------
DROP TABLE IF EXISTS `SYS_USER`;
CREATE TABLE `SYS_USER` (
  `ID` VARCHAR(20) DEFAULT NULL COMMENT 'ID',
  `LOGINNAME` VARCHAR(50) DEFAULT NULL COMMENT '用户账号',
  `PASSWORD` VARCHAR(100) DEFAULT NULL COMMENT '用户密码',
  `CREATE_TIME` DATETIME DEFAULT NULL COMMENT '创建时间',
  `LOGIN_TIME` DATETIME DEFAULT NULL COMMENT '登录时间'
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT=' 用户表';

-- ----------------------------
-- TABLE STRUCTURE FOR GD_GOODS
-- ----------------------------
DROP TABLE IF EXISTS `GD_GOODS`;
CREATE TABLE `GD_GOODS` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `SERIAL` VARCHAR(50) DEFAULT NULL COMMENT '序列号',
  `NAME` VARCHAR(120) DEFAULT NULL COMMENT '名称',
  `STORE` VARCHAR(100) DEFAULT NULL COMMENT '店名',
  `STORE_TYPE` VARCHAR(10) DEFAULT NULL COMMENT '店家类型',
  `IMAGE_PATH` VARCHAR(200) DEFAULT NULL COMMENT '图片地址',
  `PRICE` DECIMAL(10,2) DEFAULT NULL COMMENT '原价',
  `DISCOUNT` DECIMAL(10,2) DEFAULT NULL COMMENT '优惠价',
  `TORDER` VARCHAR(200) DEFAULT NULL COMMENT '淘口令',
  `LINK1` VARCHAR(200) DEFAULT NULL COMMENT '链接1',
  `LINK2` VARCHAR(200) DEFAULT NULL COMMENT '链接2',
  `LINK3` VARCHAR(200) DEFAULT NULL COMMENT '链接3',
  `START_TIME` DATETIME DEFAULT NULL COMMENT '开始时间',
  `END_TIME` DATETIME DEFAULT NULL COMMENT '结束时间',
  `CREATE_TIME` DATETIME DEFAULT NULL COMMENT '创建时间',
  `STATUS` INT(11) DEFAULT NULL COMMENT '状态',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 COMMENT='商品';
